version: '3'
services:
  python3.6:
    image: python:3.6.6
    volumes:
      - $PWD:$PWD
    environment:
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    command: bash -c "pip3 install -r requirements.txt >/dev/null"
    working_dir: $PWD
    entrypoint: bash -c

  
